### ISSUE TITLE
Unable to run the kitchensink example

### ISSUE THREAD

**Issue by huylenq** [drcode/blueprint-cljs#1]
Running the figwheel script causing "Could not find artifact org.omcljs:om:jar:1.0.0-addonsalpha48-SNAPSHOT in clojars (https://clojars.org/repo/)"

**Comment by williballenthin** [comment]
best as i could figure out was that this is a test to ensure the reader is paying attention. browsing clojars.org doesn't show any snapshots following the above naming scheme.

i solved the issue by following the instructions for Om with Addons found here: https://github.com/omcljs/om#react-with-add-ons

**Comment by huylenq** [comment]
Thanks, I know that artifact is not in any public repo but I still think a template project should be made to be easier to get up and running.

**Comment by drcode** [comment]
Hi, I'll look into this today- Thanks for bringing it to my attention.

**Comment by drcode** [comment]
Sorry for the delay, now fixed in master branch.
